version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /tests/evals
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /app/src-tauri
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /app/src-tauri
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
