/**
 * E2E tests for the Refine page.
 *
 * Tests use the E2E mock layer (TAURI_E2E=true) to replace Tauri
 * commands with in-memory responses. Agent lifecycle events are
 * dispatched through the agent simulator, exercising the same code
 * paths the real sidecar would trigger.
 *
 * The refine page gets its agentId from the `send_refine_message`
 * mock response (generated by the backend). Tests read the agentId
 * from the rendered `data-agent-id` attribute on the thinking
 * indicator / agent turn element.
 */
import { test, expect, type Page } from "@playwright/test";
import { emitTauriEvent, simulateAgentRun, simulateAgentError } from "../helpers/agent-simulator";
import { navigateToRefineWithSkill } from "../helpers/refine-helpers";

/**
 * After clicking send, wait for the thinking indicator then read the
 * dynamically-generated agent ID from the DOM.
 */
async function getAgentId(page: Page): Promise<string> {
  const thinking = page.getByTestId("refine-agent-thinking");
  await thinking.waitFor({ timeout: 5_000 });
  const agentId = await thinking.getAttribute("data-agent-id");
  if (!agentId) throw new Error("Could not read agent ID from thinking indicator");
  return agentId;
}

test.describe("Refine Page", { tag: "@refine" }, () => {
  test("slash command /rewrite shows badge and sends command", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");

    // Type "/" to trigger command picker
    await input.press("/");
    await expect(page.getByRole("listbox")).toBeVisible();

    // Command picker should open with both options
    await expect(page.getByRole("option", { name: /rewrite skill/i })).toBeVisible();
    await expect(page.getByRole("option", { name: /validate skill/i })).toBeVisible();

    // Select "Rewrite skill"
    await page.getByRole("option", { name: /rewrite skill/i }).click();

    // /rewrite badge should appear
    await expect(page.getByTestId("refine-command-badge")).toBeVisible();
    await expect(page.getByTestId("refine-command-badge")).toContainText("/rewrite");

    // Type additional instructions
    await input.fill("improve structure");

    // Send
    await input.press("Enter");

    // User message in chat should show the /rewrite badge
    await expect(page.getByText("/rewrite").last()).toBeVisible();

    // Read agentId and simulate agent
    const agentId = await getAgentId(page);
    await simulateAgentRun(page, {
      agentId,
      messages: ["Rewriting skill with improved structure..."],
      result: "Rewrite complete.",
    });

    await expect(page.getByText("Rewriting skill with improved structure...").last()).toBeVisible();
  });

  test("happy path: select skill, send message, open modified file, and return to chat", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // --- 1. Verify skill loaded ---
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();

    // --- 2. Send a refinement message ---
    const input = page.getByTestId("refine-chat-input");
    await input.fill("add a quick-start section");
    await page.getByTestId("refine-send-button").click();

    // User message visible in chat
    await expect(page.getByText("add a quick-start section")).toBeVisible();

    // --- 3. Get agent ID from thinking indicator ---
    const agentId = await getAgentId(page);

    // --- 4. Swap mock to return modified files (simulates agent edits) ---
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      const files = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
      overrides.finalize_refine_run = {
        files,
        diff: {
          stat: "1 file changed",
          files: [{
            path: "test-skill/SKILL.md",
            status: "modified",
            diff: "diff --git a/SKILL.md b/SKILL.md\n--- a/SKILL.md\n+++ b/SKILL.md\n@@ -1,5 +1,9 @@\n # Test Skill\n \n A skill for testing.\n+\n+## Quick Start\n+\n+Get started in 3 steps.\n \n ## Instructions\n",
          }],
        },
        commit_sha: null,
      };
    });

    // --- 5. Simulate agent run ---
    await simulateAgentRun(page, {
      agentId,
      messages: [
        "Reading SKILL.md...",
        "Added a Quick Start section with getting-started steps.",
      ],
      result: "Refinement complete.",
    });

    // --- 6. Verify agent output appears ---
    await expect(
      page.getByText("Added a Quick Start section with getting-started steps.").last(),
    ).toBeVisible();

    // Thinking indicator gone
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();

    // --- 7. Verify modified-file pills are shown ---
    await expect(page.getByTestId("refine-modified-files")).toBeVisible();
    const skillPill = page.getByTestId("refine-modified-file-pill-SKILL.md");
    await expect(skillPill).toBeVisible();

    // --- 8. Open the modified file view ---
    await skillPill.click();
    await expect(page.getByTestId("refine-file-view")).toBeVisible();
    await expect(page.getByTestId("refine-file-view-title")).toContainText("SKILL.md");
    await expect(page.getByTestId("refine-chat-input")).not.toBeVisible();

    // --- 9. Toggle diff mode inside the file view ---
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(diffToggle).toContainText("Preview");

    // --- 10. Return to the chat ---
    await page.getByTestId("refine-file-view-back").click();
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();
    await expect(page.getByText("add a quick-start section")).toBeVisible();
  });

  test("agent error mid-refine: error renders, chat usable, diff preserved", async ({ page }) => {
    // --- Turn 1 (successful): Add Quick Start section ---
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("improve intro");
    await page.getByTestId("refine-send-button").click();

    const agentId1 = await getAgentId(page);

    // Swap mocks to return modified SKILL.md with Quick Start
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      const files = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
      overrides.get_skill_content_for_refine = files;
      overrides.finalize_refine_run = {
        files,
        diff: {
          stat: "1 file changed",
          files: [{
            path: "test-skill/SKILL.md",
            status: "modified",
            diff: "diff --git a/SKILL.md b/SKILL.md\n--- a/SKILL.md\n+++ b/SKILL.md\n@@ -1,5 +1,9 @@\n # Test Skill\n \n A skill for testing.\n+\n+## Quick Start\n+\n+Get started in 3 steps.\n \n ## Instructions\n",
          }],
        },
        commit_sha: null,
      };
    });

    await simulateAgentRun(page, {
      agentId: agentId1,
      messages: ["Improving intro..."],
      result: "Done.",
    });

    // Wait for agent to finish and files to reload (updateSkillFiles is async)
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();
    const skillPill = page.getByTestId("refine-modified-file-pill-SKILL.md");
    await expect(skillPill).toBeVisible();

    // Verify diff toggle enabled and turn 1 diff works
    await skillPill.click();
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(page.getByTestId("git-patch-line-added").filter({ hasText: "## Quick Start" })).toBeVisible();
    await page.getByTestId("refine-file-view-back").click();

    // --- Turn 2 (error): Agent fails before modifying files ---
    // Swap send_refine_message mock to return a new agent ID
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.send_refine_message = "refine-error-e2e-001";
    });

    // Do NOT change get_skill_content_for_refine mock (agent fails before modifying files)
    await input.fill("add more content");
    await page.getByTestId("refine-send-button").click();

    const agentId2 = await getAgentId(page);
    expect(agentId2).toBe("refine-error-e2e-001");

    // Simulate agent error (init_start → sdk_ready → exit with success=false)
    await simulateAgentError(page, agentId2);

    // Verify error toast
    await expect(page.getByText("Agent failed — check the chat for details").first()).toBeVisible();

    // Verify chat input is still enabled (user can retry)
    await expect(page.getByTestId("refine-chat-input")).toBeEnabled();

    // Turn 2 clears the stale turn 1 modified-file pills immediately
    await expect(page.getByTestId("refine-modified-files")).not.toBeVisible();
  });

  test("multi-file refine run keeps the selected file aligned with Preview/Diff", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("rewrite both files");
    await page.getByTestId("refine-send-button").click();

    const agentId = await getAgentId(page);

    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      const files = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Updated definition" },
      ];
      overrides.get_skill_content_for_refine = files;
      overrides.finalize_refine_run = {
        files,
        diff: {
          stat: "2 files changed",
          files: [
            {
              path: "test-skill/SKILL.md",
              status: "modified",
              diff: "diff --git a/SKILL.md b/SKILL.md\n--- a/SKILL.md\n+++ b/SKILL.md\n@@ -1,5 +1,9 @@\n # Test Skill\n \n A skill for testing.\n+\n+## Quick Start\n+\n+Get started in 3 steps.\n \n ## Instructions\n",
            },
            {
              path: "test-skill/references/glossary.md",
              status: "modified",
              diff: "diff --git a/references/glossary.md b/references/glossary.md\n--- a/references/glossary.md\n+++ b/references/glossary.md\n@@ -1,2 +1,2 @@\n # Glossary\n \n-- **Term**: Definition\n+- **Term**: Updated definition\n",
            },
          ],
        },
        commit_sha: null,
      };
    });

    await simulateAgentRun(page, {
      agentId,
      messages: ["Updating the skill and glossary..."],
      result: "Done.",
    });

    const glossaryPill = page.getByTestId("refine-modified-file-pill-references/glossary.md");
    await expect(glossaryPill).toBeVisible();
    await glossaryPill.click();

    await expect(page.getByTestId("refine-file-view-title")).toContainText("references/glossary.md");
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(page.getByTestId("git-patch-view")).toContainText("Updated definition");
    await expect(page.getByTestId("refine-file-view-title")).toContainText("references/glossary.md");

    await page.getByTestId("refine-file-view-back").click();
    await page.getByTestId("refine-modified-file-pill-SKILL.md").click();
    await expect(page.getByTestId("refine-file-view-title")).toContainText("SKILL.md");
  });

  test("tab-switch guard blocks leaving refine while agent is running", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("keep refining");
    await page.getByTestId("refine-send-button").click();

    await getAgentId(page);

    await page.getByRole("tab", { name: "Overview" }).click();
    await expect(page.getByRole("heading", { name: "Agent Running" })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText("A refine agent is still running. Switching tabs will abandon it.")).toBeVisible();

    await page.getByRole("button", { name: "Stay" }).click();
    await expect(page.getByRole("heading", { name: "Agent Running" })).not.toBeVisible();
    await expect(page.getByRole("tab", { name: "Refine", exact: true })).toHaveAttribute("data-state", "active");
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();

    await page.getByRole("tab", { name: "Overview" }).click();
    await expect(page.getByRole("heading", { name: "Agent Running" })).toBeVisible({ timeout: 5_000 });
    await page.getByRole("button", { name: "Leave" }).click();

    await expect(page.getByRole("heading", { name: "Agent Running" })).not.toBeVisible();
    await expect(page.getByRole("tab", { name: "Overview" })).toHaveAttribute("data-state", "active");
  });

  test("close-requested shows the refine abandonment dialog while agent is running", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("trigger close guard");
    await page.getByTestId("refine-send-button").click();

    await getAgentId(page);

    await emitTauriEvent(page, "close-requested", null);
    await expect(page.getByRole("heading", { name: "Agents Still Running" })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText("One or more agents are still running. Closing now will stop them.")).toBeVisible();
    await expect(page.getByRole("button", { name: "Stay" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Close Anyway" })).toBeVisible();

    await page.getByRole("button", { name: "Stay" }).click();
    await expect(page.getByRole("heading", { name: "Agents Still Running" })).not.toBeVisible();
  });
});
