/**
 * E2E tests for the Refine page.
 *
 * Tests use the E2E mock layer (TAURI_E2E=true) to replace Tauri
 * commands with in-memory responses. Agent lifecycle events are
 * dispatched through the agent simulator, exercising the same code
 * paths the real sidecar would trigger.
 *
 * The refine page gets its agentId from the `send_refine_message`
 * mock response (generated by the backend). Tests read the agentId
 * from the rendered `data-agent-id` attribute on the thinking
 * indicator / agent turn element.
 */
import { test, expect, type Page } from "@playwright/test";
import { emitTauriEvent, simulateAgentRun, simulateAgentError } from "../helpers/agent-simulator";
import { navigateToRefineWithSkill } from "../helpers/refine-helpers";

/**
 * After clicking send, wait for the thinking indicator then read the
 * dynamically-generated agent ID from the DOM.
 */
async function getAgentId(page: Page): Promise<string> {
  const thinking = page.getByTestId("refine-agent-thinking");
  await thinking.waitFor({ timeout: 5_000 });
  const agentId = await thinking.getAttribute("data-agent-id");
  if (!agentId) throw new Error("Could not read agent ID from thinking indicator");
  return agentId;
}

async function trackInvokes(page: Page, commands: string[]): Promise<void> {
  await page.evaluate((cmds) => {
    const w = window as unknown as Record<string, unknown>;
    w.__TAURI_TRACK_INVOKES__ = cmds;
    w.__TAURI_TRACKED_INVOKES__ = [];
  }, commands);
}

async function getTrackedInvokes(
  page: Page,
  cmd: string,
): Promise<Array<{ cmd: string; args: Record<string, unknown> }>> {
  const all = await page.evaluate(() => {
    return ((window as unknown as Record<string, unknown>).__TAURI_TRACKED_INVOKES__ ?? []) as Array<{
      cmd: string;
      args: Record<string, unknown>;
    }>;
  });
  return all.filter((entry) => entry.cmd === cmd);
}

test.describe("Refine Page", { tag: "@refine" }, () => {
  test("quick-action button prefills input and sends message", async ({ page }) => {
    await navigateToRefineWithSkill(page);
    await trackInvokes(page, ["send_refine_message"]);

    // Click the "Validate this skill" quick-action button — prefills input
    await page.getByRole("button", { name: "Validate this skill" }).click();
    const input = page.getByTestId("refine-chat-input");
    await expect(input).toContainText("Validate this skill");

    // Send the prefilling quick-action through the same explicit button path used elsewhere.
    await page.getByTestId("refine-send-button").click();

    const invokes = await getTrackedInvokes(page, "send_refine_message");
    expect(invokes).toHaveLength(1);
    expect(invokes[0]?.args.command).toBeNull();
    expect(invokes[0]?.args.userMessage).toBe("Validate this skill");

    // Read agentId and simulate agent
    const agentId = await getAgentId(page);
    await simulateAgentRun(page, {
      agentId,
      messages: ["Running validation checks..."],
      result: "Validation complete.",
    });

    await expect(page.getByText("Running validation checks...").last()).toBeVisible();
  });

  test("happy path: select skill, send message, open modified file, and close the side viewer", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    // --- 1. Verify skill loaded ---
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();

    // --- 2. Send a refinement message ---
    const input = page.getByTestId("refine-chat-input");
    await input.fill("add a quick-start section");
    await page.getByTestId("refine-send-button").click();

    // User message visible in chat
    await expect(page.getByText("add a quick-start section")).toBeVisible();

    // --- 3. Get agent ID from thinking indicator ---
    const agentId = await getAgentId(page);

    // --- 4. Swap mock to return modified files (simulates agent edits) ---
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      const files = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
      overrides.get_skill_content_for_refine = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
      overrides.finalize_refine_run = {
        files,
        diff: {
          stat: "1 file changed",
          files: [{
            path: "test-skill/SKILL.md",
            status: "modified",
            diff: "diff --git a/SKILL.md b/SKILL.md\n--- a/SKILL.md\n+++ b/SKILL.md\n@@ -1,5 +1,9 @@\n # Test Skill\n \n A skill for testing.\n+\n+## Quick Start\n+\n+Get started in 3 steps.\n \n ## Instructions\n",
          }],
        },
        commit_sha: null,
      };
    });

    // --- 5. Simulate agent run ---
    await simulateAgentRun(page, {
      agentId,
      messages: [
        "Reading SKILL.md...",
        "Added a Quick Start section with getting-started steps.",
      ],
      result: "Refinement complete.",
    });

    // --- 6. Verify agent output appears ---
    await expect(
      page.getByText("Added a Quick Start section with getting-started steps.").last(),
    ).toBeVisible();

    // Thinking indicator gone
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();

    // --- 7. Verify modified-file pills are shown ---
    await expect(page.getByTestId("refine-modified-files")).toBeVisible();
    const skillPill = page.getByTestId("refine-modified-file-pill-SKILL.md");
    await expect(skillPill).toBeVisible();

    // --- 8. Open the modified file view ---
    await skillPill.click();
    await expect(page.getByTestId("refine-file-view")).toBeVisible();
    await expect(page.getByTestId("refine-file-view-title")).toContainText("SKILL.md");
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();

    // --- 9. Toggle diff mode inside the file view ---
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(diffToggle).toContainText("Preview");

    // --- 10. Close the side viewer ---
    await page.getByTestId("refine-file-view-close").click();
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();
    await expect(page.getByText("add a quick-start section")).toBeVisible();
    await expect(page.getByTestId("refine-file-view")).not.toBeVisible();
  });

  test("agent error mid-refine: error renders, chat usable, diff preserved", async ({ page }) => {
    // --- Turn 1 (successful): Add Quick Start section ---
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("improve intro");
    await page.getByTestId("refine-send-button").click();

    const agentId1 = await getAgentId(page);

    // Swap mocks to return modified SKILL.md with Quick Start
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      const files = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Definition" },
      ];
      overrides.get_skill_content_for_refine = files;
      overrides.finalize_refine_run = {
        files,
        diff: {
          stat: "1 file changed",
          files: [{
            path: "test-skill/SKILL.md",
            status: "modified",
            diff: "diff --git a/SKILL.md b/SKILL.md\n--- a/SKILL.md\n+++ b/SKILL.md\n@@ -1,5 +1,9 @@\n # Test Skill\n \n A skill for testing.\n+\n+## Quick Start\n+\n+Get started in 3 steps.\n \n ## Instructions\n",
          }],
        },
        commit_sha: null,
      };
    });

    await simulateAgentRun(page, {
      agentId: agentId1,
      messages: ["Improving intro..."],
      result: "Done.",
    });

    // Wait for agent to finish and files to reload (updateSkillFiles is async)
    await expect(page.getByTestId("refine-agent-thinking")).not.toBeVisible();
    const skillPill = page.getByTestId("refine-modified-file-pill-SKILL.md");
    await expect(skillPill).toBeVisible();

    // Verify diff toggle enabled and turn 1 diff works
    await skillPill.click();
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(page.getByTestId("git-patch-line-added").filter({ hasText: "## Quick Start" })).toBeVisible();
    await page.getByTestId("refine-file-view-close").click();

    // --- Turn 2 (error): Agent fails before modifying files ---
    // Swap send_refine_message mock to return a new agent ID
    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      overrides.send_refine_message = "refine-error-e2e-001";
    });

    // Do NOT change get_skill_content_for_refine mock (agent fails before modifying files)
    await input.fill("add more content");
    await page.getByTestId("refine-send-button").click();

    const agentId2 = await getAgentId(page);
    expect(agentId2).toBe("refine-error-e2e-001");

    // Simulate agent error (init_start → sdk_ready → exit with success=false)
    await simulateAgentError(page, agentId2);

    // Verify error toast
    await expect(page.getByText("Agent failed — check the chat for details").first()).toBeVisible();

    // Verify chat input is still enabled (user can retry)
    await expect(page.getByTestId("refine-chat-input")).toBeEnabled();

    // The last successful diff remains available even if the next refine turn fails.
    await expect(page.getByTestId("refine-modified-files")).toBeVisible();
    await expect(page.getByTestId("refine-modified-file-pill-SKILL.md")).toBeVisible();
  });

  test("multi-file refine run keeps the selected file aligned with Preview/Diff", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("rewrite both files");
    await page.getByTestId("refine-send-button").click();

    const agentId = await getAgentId(page);

    await page.evaluate(() => {
      const overrides = (window as unknown as Record<string, unknown>).__TAURI_MOCK_OVERRIDES__ as Record<string, unknown>;
      const files = [
        {
          path: "SKILL.md",
          content: "# Test Skill\n\nA skill for testing.\n\n## Quick Start\n\nGet started in 3 steps.\n\n## Instructions\n\nFollow these steps...",
        },
        { path: "references/glossary.md", content: "# Glossary\n\n- **Term**: Updated definition" },
      ];
      overrides.get_skill_content_for_refine = files;
      overrides.finalize_refine_run = {
        files,
        diff: {
          stat: "2 files changed",
          files: [
            {
              path: "test-skill/SKILL.md",
              status: "modified",
              diff: "diff --git a/SKILL.md b/SKILL.md\n--- a/SKILL.md\n+++ b/SKILL.md\n@@ -1,5 +1,9 @@\n # Test Skill\n \n A skill for testing.\n+\n+## Quick Start\n+\n+Get started in 3 steps.\n \n ## Instructions\n",
            },
            {
              path: "test-skill/references/glossary.md",
              status: "modified",
              diff: "diff --git a/references/glossary.md b/references/glossary.md\n--- a/references/glossary.md\n+++ b/references/glossary.md\n@@ -1,2 +1,2 @@\n # Glossary\n \n-- **Term**: Definition\n+- **Term**: Updated definition\n",
            },
          ],
        },
        commit_sha: null,
      };
    });

    await simulateAgentRun(page, {
      agentId,
      messages: ["Updating the skill and glossary..."],
      result: "Done.",
    });

    const glossaryPill = page.getByTestId("refine-modified-file-pill-references/glossary.md");
    await expect(glossaryPill).toBeVisible();
    await glossaryPill.click();

    await expect(page.getByTestId("refine-file-view-title")).toContainText("references/glossary.md");
    const diffToggle = page.getByTestId("refine-diff-toggle");
    await expect(diffToggle).toBeEnabled();
    await diffToggle.click();
    await expect(page.getByTestId("git-patch-view")).toContainText("Updated definition");
    await expect(page.getByTestId("refine-file-view-title")).toContainText("references/glossary.md");

    await page.getByTestId("refine-file-view-close").click();
    await page.getByTestId("refine-modified-file-pill-SKILL.md").click();
    await expect(page.getByTestId("refine-file-view-title")).toContainText("SKILL.md");
  });

  test("agent-led redirect asks inline and launches validate after confirmation", async ({ page }) => {
    await navigateToRefineWithSkill(page);
    await trackInvokes(page, ["send_refine_message", "answer_refine_question"]);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("can you review this skill for issues?");
    await page.getByTestId("refine-send-button").click();

    const agentId = await getAgentId(page);

    await emitTauriEvent(page, "agent-message", {
      agent_id: agentId,
      message: {
        type: "refine_question",
        tool_use_id: "toolu_redirect",
        questions: [
          {
            header: "Next Step",
            question: "This looks more like validation. What should I do?",
            options: [
              { label: "Launch validate", description: "Run the validation agent now." },
              { label: "Clarify refine", description: "Explain what should be rewritten." },
            ],
          },
        ],
      },
    });

    await expect(page.getByTestId("refine-question-inline")).toBeVisible();
    await page.getByRole("button", { name: /launch validate/i }).click();
    await page.getByTestId("refine-question-submit").click();

    const answerCalls = await getTrackedInvokes(page, "answer_refine_question");
    expect(answerCalls).toHaveLength(1);
    expect(answerCalls[0]?.args.toolUseId).toBe("toolu_redirect");

    await emitTauriEvent(page, "agent-exit", {
      agent_id: agentId,
      success: true,
    });

    await expect.poll(async () => {
      const calls = await getTrackedInvokes(page, "send_refine_message");
      return calls.length;
    }).toBe(2);

    const sendCalls = await getTrackedInvokes(page, "send_refine_message");
    expect(sendCalls[0]?.args.command).toBeNull();
    expect(sendCalls[1]?.args.command).toBeNull();
    expect(sendCalls[1]?.args.userMessage).toBe("validate this skill: can you review this skill for issues?");
  });

  test("tab-switch guard blocks leaving refine while agent is running", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("keep refining");
    await page.getByTestId("refine-send-button").click();

    await getAgentId(page);

    await page.getByRole("tab", { name: "Overview" }).click();
    await expect(page.getByRole("heading", { name: "Agent Running" })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText("A refine agent is still running. Switching tabs will abandon it.")).toBeVisible();

    await page.getByRole("button", { name: "Stay" }).click();
    await expect(page.getByRole("heading", { name: "Agent Running" })).not.toBeVisible();
    await expect(page.getByRole("tab", { name: "Refine", exact: true })).toHaveAttribute("data-state", "active");
    await expect(page.getByTestId("refine-chat-input")).toBeVisible();

    await page.getByRole("tab", { name: "Overview" }).click();
    await expect(page.getByRole("heading", { name: "Agent Running" })).toBeVisible({ timeout: 5_000 });
    await page.getByRole("button", { name: "Leave" }).click();

    await expect(page.getByRole("heading", { name: "Agent Running" })).not.toBeVisible();
    await expect(page.getByRole("tab", { name: "Overview" })).toHaveAttribute("data-state", "active");
  });

  test("close-requested shows the refine abandonment dialog while agent is running", async ({ page }) => {
    await navigateToRefineWithSkill(page);

    const input = page.getByTestId("refine-chat-input");
    await input.fill("trigger close guard");
    await page.getByTestId("refine-send-button").click();

    await getAgentId(page);

    await emitTauriEvent(page, "close-requested", null);
    await expect(page.getByRole("heading", { name: "Agent Still Running" })).toBeVisible({ timeout: 5_000 });
    await expect(page.getByText("An agent is still running. Close anyway?")).toBeVisible();
    await expect(page.getByRole("button", { name: "Stay" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Close Anyway" })).toBeVisible();

    await page.getByRole("button", { name: "Stay" }).click();
    await expect(page.getByRole("heading", { name: "Agent Still Running" })).not.toBeVisible();
  });
});
